DROP TABLE IF EXISTS tweet;
DROP TABLE IF EXISTS records;

CREATE TABLE tweet(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  tweetID INTEGER NOT NULL,
  tweetText TEXT NOT NULL
);

CREATE TABLE records(
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  userID TEXT NOT NULL,
  tweetID INTEGER NOT NULL,
  FOREIGN KEY (tweetID) REFERENCES tweet (tweetID)
);
